version: '2.2'

services:
  versewise-cms-backend:
    container_name: versewise-cms-backend
    build:
      context: .
    ports:
      - "${HOST_PORT}:5000"
    env_file:
      - .env
    volumes:
      - .:/versewise-cms-backend
    restart: unless-stopped
    networks:
      - versewise-networks

networks:
  versewise-networks:
    driver: bridge
